import { stock_products } from '@prisma/client';
export * as usersRepository from './users/usersRepository';
export * as favoritedsRepository from './products/favoritedsRepository';
export * as productsRepository from './products/productsRepository';
export * as addressesRepository from './users/addressesRepository';
export * as stockRepository from './stock/stockRepository';
export * as categoriesRepository from './categories/categoriesRepository';
export * as ordersRepository from './orders/ordersRepository';
export * as stock_products from './middleTables/stock_products';
